//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AbstractMetricsFactory.java
//  @ Date : 10/05/2007
//  @ Author : 
//
//




public class AbstractMetricsFactory 
{
	public void GetMetricsFactory(string type) 
	{
	
	}
}
