package com.codesquale.metrics;

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IMetricsFactory.java
//  @ Date : 10/05/2007
//  @ Author : 
//
//




public interface IMetricsFactory 
{
	public void GenereateResultsFile();
}
