package com.codesquale.metrics;

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SaxonMetricsFactory.java
//  @ Date : 10/05/2007
//  @ Author : 
//
//




public class SaxonMetricsFactory extends IMetricsFactory 
{
	public void GenereateResultsFile() 
	{
	
	}
}
